const ACTIONS = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    SEND_MESSAGE: "SEND_MESSAGE",
    FETCH_MESSAGE: "FETCH_MESSAGE",
    CHANGE_CHAT_BOX: "CHANGE_CHAT_BOX",
    RECEIVE_MESSAGE: "RECEIVE_MESSAGE",
    ADD_CONTACT: "ADD_CONTACT",
    FETCH_CHATBOX: "FETCH_CHATBOX",
    ADD_CHATBOX: "ADD_CHATBOX",
    ADD_NEW_MESSAGE_TO_CHATBOX: "ADD_NEW_MESSAGE_TO_CHATBOX"
}

export default ACTIONS