const ACTIONS = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    SEND_MESSAGE: "SEND_MESSAGE",
    FETCH_MESSAGE: "FETCH_MESSAGE",
    CHANGE_CHAT_BOX: "CHANGE_CHAT_BOX",
    RECEIVE_MESSAGE: "RECEIVE_MESSAGE"
}

export default ACTIONS